"""
Django settings for screener_project project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from datetime import timedelta
import os
from pathlib import Path
import sys
from django.utils import timezone

AUTH_USER_MODEL = 'screener_api.User'

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY ='$fhn7#caayy($flb(ce!(j%$c5iq=5n!^d58xk=@cp6&aw7dw@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'screener_api',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework', # Django REST Framework
    'rest_framework_simplejwt',
    'corsheaders', 
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'screener_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'screener_project.wsgi.application'

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000", # Allow your React development server
    # Add other origins for your frontend in production (e.g., "https://yourfrontenddomain.com")
]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False, # Keep this False to allow libraries (like yfinance, hmmlearn) to log
    'formatters': {
        'verbose': {
            'format': '{asctime} - {levelname} - {module} - {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{', 
        },
    },
    'handlers': {
        'file': {
            'level': 'DEBUG', # Log everything >= DEBUG to file
            'class': 'logging.FileHandler',
            # screener.log will be created in the BASE_DIR (where manage.py is)
            'filename': os.path.join(BASE_DIR, 'screener.log'),
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO', # Log >= INFO to console
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
            'stream': sys.stdout, # Explicitly set stream to stdout
        },
    },
    # Configure root logger
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO', # Default level for loggers without specific config
    },
    # Configure screener_api logger specifically
    'loggers': {
        'screener_api': {
            'handlers': ['console', 'file'],
            # Set a lower level for your app's logs if needed for debugging
            # Setting to DEBUG will log all DEBUG messages from screener_logic
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False, # Prevent logs from propagating to the root logger (already handled here)
        },
        # Optional: configure loggers for libraries if they are too noisy
        # 'yfinance': {
        #     'handlers': ['file'], # Log only yfinance errors/warnings to file
        #     'level': 'WARNING',
        #     'propagate': False,
        # },
        # 'hmmlearn': {
        #     'handlers': ['file'], # Log hmmlearn errors/warnings to file
        #     'level': 'WARNING',
        #     'propagate': False,
        # },
         'urllib3': { # Often noisy from libraries like yfinance or axios under the hood
            'handlers': ['file'],
            'level': 'WARNING',
            'propagate': False,
         }
    },
}


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        # FIX 1: Use os.path.join for string path concatenation
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SCREENER_CONFIG_PATH = os.path.join(BASE_DIR, 'config.json')
SCREENER_CACHE_DIR = os.path.join(BASE_DIR, 'data_cache')
SCREENER_LOG_PATH = os.path.join(BASE_DIR, 'screener.log')


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
}

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST_USER = 'rahulprasadkpm@gmail.com'
EMAIL_HOST_PASSWORD = 'fuiy gsvy ijwq ifpx'
FRONTEND_URL = 'http://localhost:3000'

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
}


# settings.py

